apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-service-config
  namespace: audit-evidence
data:
  NODE_ENV: "production"
  PORT: "3000"
  AWS_REGION: "us-east-1"
  LOG_LEVEL: "info"
  DB_POOL_SIZE: "10"
  COLLECTION_SCHEDULE: "0 2 * * *"