apiVersion: v1
kind: Secret
metadata:
  name: audit-service-secrets
  namespace: audit-evidence
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: cG9zdGdyZXNxbDovL2F1ZGl0X3VzZXI6YXVkaXRfcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9hdWRpdF9ldmlkZW5jZQ==
  AWS_ACCESS_KEY_ID: WU9VUl9BV1NfQUNDRVNTX0tFWV9JRA==
  AWS_SECRET_ACCESS_KEY: WU9VUl9BV1NfU0VDUkVUX0FDQ0VTU19LRVk=
  AWS_S3_BUCKET: YXVkaXQtZXZpZGVuY2UtYnVja2V0
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  ENCRYPTION_KEY: eW91ci0zMi1jaGFyYWN0ZXItZW5jcnlwdGlvbi1rZXkhIQ==
  BEARER_TOKEN: eW91ci1iZWFyZXItdG9rZW4tY2hhbmdlLWluLXByb2R1Y3Rpb24=